### ISSUE TITLE
record timeout into jsons when request timeout

### ISSUE THREAD

**Issue by KazuCocoa** [KazuCocoa/http_proxy#3]
When we get timeout error, then store the result on the json file.

```
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :timeout}
        (http_proxy) lib/http_proxy/handle.ex:94: HttpProxy.Handle.read_proxy/2
        (http_proxy) lib/http_proxy/handle.ex:1: HttpProxy.Handle.plug_builder_call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by KazuCocoa** [comment]
https://github.com/KazuCocoa/http_proxy/commit/0b55b4f5ebe78c1824e97758fbccf6c1b2728bcf
